# Appendix { - }

## Previous offerings {-}

### Videos from August, 2021 {-}

The inaugural offering of this material was in August 2021, co-hosted
by the UC Davis DataLab and the NIH Common Fund Data Ecosystem.  The
material from that workshop is hosted
[here](https://ngs-docs.github.io/2021-august-remote-computing/), and
all the sessions were recorded; videos below!

[Video: Introduction to the UNIX Command Line](https://video.ucdavis.edu/media/Intro+to+the+UNIX+Command+Line/1_lcij2vm2)

[Video: Creating and modifying text files on remote computers](https://video.ucdavis.edu/media/Creating+and+Modifying+Text+Files+on+Remote+Computers/1_z0lantu4)

[Video: Connecting to remote computers with ssh](https://video.ucdavis.edu/media/Connecting+to+Remote+Computers+with+SSH/1_806ws8at)
[Video: Running programs on remote computers and retrieving the results](https://video.ucdavis.edu/media/Running+Programs+on+Remote+Computers+and+Retrieving+Results/1_6wvl21uo)
[Video: Installing software on remote computers with conda](https://video.ucdavis.edu/media/Installing+Software+on+Remote+Computers+with+Conda/1_c5phpz6m)
[Video: Structuring your projects for current and future you](https://video.ucdavis.edu/media/Structuring+Your+Projects+for+Current+and+Future+You+-+Workshop+6/1_48prhl9s)
[Video: Automating your analyses and executing long-running analyses on remote computers](https://video.ucdavis.edu/media/Workshop+7A+Automating+Your+Analyses+and+Executing+Long-Running+Analyses+on+Remote+Computers/1_u4mwpvys)
[Video: Keeping track of your files with version control](https://video.ucdavis.edu/media/Workshop+8A+Keeping+Track+of+Your+Files+with+Version+Control/1_t8s68r43)
[Video: Automating your analyses with the snakemake workflow system](https://video.ucdavis.edu/media/Workshop+9A+Automating+Your+Analyses+with+the+Snakemake+Workflow+System/1_zvpl1v4x)
[Video: Executing large analyses on HPC clusters with slurm](https://video.ucdavis.edu/media/Workshop+10A+Executing+Large+Analyses+on+HPC+Clusters+with+Slurm/1_x50x5t77)
[Video: Making use of on-demand "cloud" computers from Amazon Web Services](https://video.ucdavis.edu/media/Workshop+11A+Making+Use+of+On-Demand+%22Cloud%22+Computers+from+Amazon+Web+Services/1_l9wfn0lj)

## Workshop Protocol { - }

**Before workshop**

- Instructor(s) create workshop notes on GitHub as an R markdown file
- Instructor(s) create/test computing environment (i.e., binder, Farm HPC) for workshop material
- Training coordinator creates pre- and post-workshop assessment surveys, with input from instructor(s)
- Training coordinator emails notes, pre-workshop survey, and Zoom link to participants the day before the workshop

**During workshop**

- Moderator begins by asking everyone to fill out the pre-workshop survey if they haven't
already, and to put up a raised hand Zoom reaction when they've completed the survey.
Then, describe ways to ask for help during the workshop: 1) type in Zoom chat to everyone or as a direct message to moderator/helpers (introduce helpers), 2) unmute and ask; say that we prefer participants don't use the raised hand reaction to ask a question, since that's used for checking in.
At this point, there should be a majority of raised hands up for the survey question. Turn over the mic to the instructor.
- Moderator will keep track of chat questions, time (including a 5-minute break ~10:15 or 10:30am), and help share workshop resource links (i.e., section of workshop notes, exercises, post-workshop survey)
- Helpers aide in tracking chat questions and participation during check ins (i.e., direct message participants who have not raised their hands to make sure they're still following along)
- Training team writes down typos, suggestions, etc. for the workshop and notes in the associated GitHub issue


**After workshop**

- Training team updates workshop notes as needed
- Training coordinator emails notes, workshop recording, and post-workshop survey link to participants some time after the workshop
